"""
SignBridge ISL Vocabulary Registry & Class Definitions
Defines all 149 recognition classes (Numbers, Alphabet, Core Words, Emergency)
with stable index ordering and English + Hindi bilingual translations.
"""

from typing import Dict, List, Any

# Numbers (0-9)
NUMBERS: List[str] = [str(i) for i in range(10)]

# Alphabet (A-Z)
ALPHABET: List[str] = [chr(c) for c in range(ord("A"), ord("Z") + 1)]

# Words (Core & Conversational)
WORDS: List[str] = [
    "After", "Again", "Against", "Age", "All", "Alone", "Also", "And", "Ask", "At",
    "Be", "Beautiful", "Before", "Best", "Better", "Busy", "But", "Bye",
    "Can", "Cannot", "Change", "College", "Come", "Computer",
    "Day", "Distance", "Do", "Do Not", "Does Not",
    "Eat", "Engineer",
    "Fight", "Finish", "From",
    "Glitter", "Go", "God", "Gold", "Good", "Great",
    "Hand", "Hands", "Happy", "Hello", "Help", "Her", "Here", "His", "Home", "Homepage", "How",
    "Invent", "It",
    "Keep",
    "Language", "Laugh", "Learn",
    "ME", "More", "My",
    "Name", "Next", "Not", "Now",
    "Of", "On", "Our", "Out",
    "Pretty",
    "Right",
    "Sad", "Safe", "See", "Self", "Sign", "Sing", "So", "Sound", "Stay", "Study",
    "Talk", "Television", "Thank", "Thank You", "That", "They", "This", "Those", "Time", "To", "Type",
    "Us",
    "Walk", "Wash", "Way", "We", "Welcome", "What", "When", "Where", "Which", "Who",
    "Whole", "Whose", "Why", "Will", "With", "Without", "Words", "Work", "World", "Wrong",
    "You", "Your", "Yourself",

    # Emergency vocabulary
    "Hospital", "Doctor", "Emergency", "Police", "Fire", "Ambulance",
    "Accident", "Pain", "Medicine", "Sick", "Injury", "Danger",
]

# Combined Master List in strictly frozen order
CLASSES: List[str] = NUMBERS + ALPHABET + WORDS

LABEL_TO_IDX: Dict[str, int] = {label: i for i, label in enumerate(CLASSES)}
IDX_TO_LABEL: Dict[int, str] = {i: label for i, label in enumerate(CLASSES)}
NUM_CLASSES: int = len(CLASSES)

# Comprehensive Bilingual Dictionary (English + Hindi)
BILINGUAL_DICT: Dict[str, Dict[str, str]] = {
    # Numbers
    "0": {"en": "Zero (0)", "hi": "शून्य (०)"},
    "1": {"en": "One (1)", "hi": "एक (१)"},
    "2": {"en": "Two (2)", "hi": "दो (२)"},
    "3": {"en": "Three (3)", "hi": "तीन (३)"},
    "4": {"en": "Four (4)", "hi": "चार (४)"},
    "5": {"en": "Five (5)", "hi": "पाँच (५)"},
    "6": {"en": "Six (6)", "hi": "छह (६)"},
    "7": {"en": "Seven (7)", "hi": "सात (७)"},
    "8": {"en": "Eight (8)", "hi": "आठ (८)"},
    "9": {"en": "Nine (9)", "hi": "नौ (९)"},

    # Alphabet
    "A": {"en": "A", "hi": "ए"},
    "B": {"en": "B", "hi": "बी"},
    "C": {"en": "C", "hi": "सी"},
    "D": {"en": "D", "hi": "डी"},
    "E": {"en": "E", "hi": "ई"},
    "F": {"en": "F", "hi": "एफ"},
    "G": {"en": "G", "hi": "जी"},
    "H": {"en": "H", "hi": "एच"},
    "I": {"en": "I", "hi": "आई"},
    "J": {"en": "J", "hi": "जे"},
    "K": {"en": "K", "hi": "के"},
    "L": {"en": "L", "hi": "एल"},
    "M": {"en": "M", "hi": "एम"},
    "N": {"en": "N", "hi": "एन"},
    "O": {"en": "O", "hi": "ओ"},
    "P": {"en": "P", "hi": "पी"},
    "Q": {"en": "Q", "hi": "क्यू"},
    "R": {"en": "R", "hi": "आर"},
    "S": {"en": "S", "hi": "एस"},
    "T": {"en": "T", "hi": "टी"},
    "U": {"en": "U", "hi": "यू"},
    "V": {"en": "V", "hi": "वी"},
    "W": {"en": "W", "hi": "डब्ल्यू"},
    "X": {"en": "X", "hi": "एक्स"},
    "Y": {"en": "Y", "hi": "वाई"},
    "Z": {"en": "Z", "hi": "ज़ेड"},

    # Core Words
    "After": {"en": "After", "hi": "बाद में"},
    "Again": {"en": "Again", "hi": "फिर से"},
    "Against": {"en": "Against", "hi": "खिलाफ"},
    "Age": {"en": "Age", "hi": "उम्र"},
    "All": {"en": "All", "hi": "सब / सभी"},
    "Alone": {"en": "Alone", "hi": "अकेला"},
    "Also": {"en": "Also", "hi": "भी"},
    "And": {"en": "And", "hi": "और"},
    "Ask": {"en": "Ask", "hi": "पूछना"},
    "At": {"en": "At", "hi": "पर"},
    "Be": {"en": "Be", "hi": "होना"},
    "Beautiful": {"en": "Beautiful", "hi": "सुंदर"},
    "Before": {"en": "Before", "hi": "पहले"},
    "Best": {"en": "Best", "hi": "सर्वश्रेष्ठ"},
    "Better": {"en": "Better", "hi": "बेहतर"},
    "Busy": {"en": "Busy", "hi": "व्यस्त"},
    "But": {"en": "But", "hi": "लेकिन"},
    "Bye": {"en": "Bye", "hi": "अलविदा"},
    "Can": {"en": "Can", "hi": "सकना"},
    "Cannot": {"en": "Cannot", "hi": "नहीं कर सकता"},
    "Change": {"en": "Change", "hi": "बदलना"},
    "College": {"en": "College", "hi": "कॉलेज"},
    "Come": {"en": "Come", "hi": "आना"},
    "Computer": {"en": "Computer", "hi": "कंप्यूटर"},
    "Day": {"en": "Day", "hi": "दिन"},
    "Distance": {"en": "Distance", "hi": "दूरी"},
    "Do": {"en": "Do", "hi": "करना"},
    "Do Not": {"en": "Do Not", "hi": "मत करो"},
    "Does Not": {"en": "Does Not", "hi": "नहीं करता"},
    "Eat": {"en": "Eat", "hi": "खाना"},
    "Engineer": {"en": "Engineer", "hi": "इंजीनियर"},
    "Fight": {"en": "Fight", "hi": "लड़ाई"},
    "Finish": {"en": "Finish", "hi": "खत्म"},
    "From": {"en": "From", "hi": "से"},
    "Glitter": {"en": "Glitter", "hi": "चमक"},
    "Go": {"en": "Go", "hi": "जाना"},
    "God": {"en": "God", "hi": "भगवान"},
    "Gold": {"en": "Gold", "hi": "सोना (स्वर्ण)"},
    "Good": {"en": "Good", "hi": "अच्छा"},
    "Great": {"en": "Great", "hi": "महान / बहुत अच्छा"},
    "Hand": {"en": "Hand", "hi": "हाथ"},
    "Hands": {"en": "Hands", "hi": "दोनों हाथ"},
    "Happy": {"en": "Happy", "hi": "खुश"},
    "Hello": {"en": "Hello", "hi": "नमस्ते"},
    "Help": {"en": "Help", "hi": "मदद"},
    "Her": {"en": "Her", "hi": "उसकी / उसे"},
    "Here": {"en": "Here", "hi": "यहाँ"},
    "His": {"en": "His", "hi": "उसका"},
    "Home": {"en": "Home", "hi": "घर"},
    "Homepage": {"en": "Homepage", "hi": "होमपेज"},
    "How": {"en": "How", "hi": "कैसे"},
    "Invent": {"en": "Invent", "hi": "आविष्कार करना"},
    "It": {"en": "It", "hi": "यह"},
    "Keep": {"en": "Keep", "hi": "रखना"},
    "Language": {"en": "Language", "hi": "भाषा"},
    "Laugh": {"en": "Laugh", "hi": "हँसना"},
    "Learn": {"en": "Learn", "hi": "सीखना"},
    "ME": {"en": "Me / I", "hi": "मैं / मुझे"},
    "More": {"en": "More", "hi": "अधिक / और"},
    "My": {"en": "My", "hi": "मेरा"},
    "Name": {"en": "Name", "hi": "नाम"},
    "Next": {"en": "Next", "hi": "अगला"},
    "Not": {"en": "Not", "hi": "नहीं"},
    "Now": {"en": "Now", "hi": "अब / अभी"},
    "Of": {"en": "Of", "hi": "का / की"},
    "On": {"en": "On", "hi": "पर"},
    "Our": {"en": "Our", "hi": "हमारा"},
    "Out": {"en": "Out", "hi": "बाहर"},
    "Pretty": {"en": "Pretty", "hi": "प्यारा / सुंदर"},
    "Right": {"en": "Right", "hi": "सही / दायाँ"},
    "Sad": {"en": "Sad", "hi": "उदास"},
    "Safe": {"en": "Safe", "hi": "सुरक्षित"},
    "See": {"en": "See", "hi": "देखना"},
    "Self": {"en": "Self", "hi": "स्वयं / खुद"},
    "Sign": {"en": "Sign", "hi": "साइन / संकेत"},
    "Sing": {"en": "Sing", "hi": "गाना"},
    "So": {"en": "So", "hi": "इसलिए / तो"},
    "Sound": {"en": "Sound", "hi": "ध्वनि / आवाज़"},
    "Stay": {"en": "Stay", "hi": "रहना / ठहरना"},
    "Study": {"en": "Study", "hi": "पढ़ाई करना"},
    "Talk": {"en": "Talk", "hi": "बात करना"},
    "Television": {"en": "Television", "hi": "टेलीविज़न"},
    "Thank": {"en": "Thank", "hi": "धन्यवाद"},
    "Thank You": {"en": "Thank You", "hi": "धन्यवाद / शुक्रिया"},
    "That": {"en": "That", "hi": "वह"},
    "They": {"en": "They", "hi": "वे / वो लोग"},
    "This": {"en": "This", "hi": "यह"},
    "Those": {"en": "Those", "hi": "वे सब"},
    "Time": {"en": "Time", "hi": "समय / वक्त"},
    "To": {"en": "To", "hi": "को / तक"},
    "Type": {"en": "Type", "hi": "टाइप करना"},
    "Us": {"en": "Us", "hi": "हमें"},
    "Walk": {"en": "Walk", "hi": "चलना"},
    "Wash": {"en": "Wash", "hi": "धोना"},
    "Way": {"en": "Way", "hi": "रास्ता / तरीका"},
    "We": {"en": "We", "hi": "हम"},
    "Welcome": {"en": "Welcome", "hi": "स्वागत"},
    "What": {"en": "What", "hi": "क्या"},
    "When": {"en": "When", "hi": "कब"},
    "Where": {"en": "Where", "hi": "कहाँ"},
    "Which": {"en": "Which", "hi": "कौन सा"},
    "Who": {"en": "Who", "hi": "कौन"},
    "Whole": {"en": "Whole", "hi": "पूरा / संपूर्ण"},
    "Whose": {"en": "Whose", "hi": "किसका"},
    "Why": {"en": "Why", "hi": "क्यों"},
    "Will": {"en": "Will", "hi": "होगा / करेगा"},
    "With": {"en": "With", "hi": "साथ"},
    "Without": {"en": "Without", "hi": "बिना"},
    "Words": {"en": "Words", "hi": "शब्द"},
    "Work": {"en": "Work", "hi": "काम"},
    "World": {"en": "World", "hi": "दुनिया"},
    "Wrong": {"en": "Wrong", "hi": "गलत"},
    "You": {"en": "You", "hi": "आप / तुम"},
    "Your": {"en": "Your", "hi": "आपका / तुम्हारा"},
    "Yourself": {"en": "Yourself", "hi": "आप खुद"},

    # Emergency Vocabulary
    "Hospital": {"en": "Hospital", "hi": "अस्पताल"},
    "Doctor": {"en": "Doctor", "hi": "डॉक्टर"},
    "Emergency": {"en": "Emergency", "hi": "आपातकाल"},
    "Police": {"en": "Police", "hi": "पुलिस"},
    "Fire": {"en": "Fire", "hi": "आग"},
    "Ambulance": {"en": "Ambulance", "hi": "एम्बुलेंस"},
    "Accident": {"en": "Accident", "hi": "दुर्घटना"},
    "Pain": {"en": "Pain", "hi": "दर्द"},
    "Medicine": {"en": "Medicine", "hi": "दवा"},
    "Sick": {"en": "Sick", "hi": "बीमार"},
    "Injury": {"en": "Injury", "hi": "चोट"},
    "Danger": {"en": "Danger", "hi": "खतरा"},
}

if __name__ == "__main__":
    print(f"Total Recognition Classes: {NUM_CLASSES}")
    print(f"  Numbers: {len(NUMBERS)} | Alphabet: {len(ALPHABET)} | Words: {len(WORDS)}")
    assert len(BILINGUAL_DICT) == NUM_CLASSES, "Mismatch between CLASSES and BILINGUAL_DICT!"
    print("All classes verified and mapped successfully.")
